# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_directions',
            field=models.CharField(default='Check back again for updated instructions', max_length=1000),
        ),
    ]
